print("IIII AMMMM AAAA KANAAAAA")
print("I never asked for your point of view")
print("I bought the shakespere fries")
print("Do I have to pee without the lights?")
print("I don't make sense anymore")
print("No the mirrors autistic")
print("It's not raining YOUR RAINING")
print("Why is there a pigeon")
print("IM SOO HUNGRYYY")
print("ISHAAAAAAAA")
print("Yes child")
